CREATE TABLE users (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(100), last_name VARCHAR(100),
 email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
 role VARCHAR(30) NOT NULL
);
CREATE TABLE locations (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, address VARCHAR(255),
 latitude DOUBLE, longitude DOUBLE, verified BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE amenities (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE);
CREATE TABLE location_amenities (location_id BIGINT NOT NULL, amenity_id BIGINT NOT NULL,
 PRIMARY KEY(location_id, amenity_id), FOREIGN KEY(location_id) REFERENCES locations(id), FOREIGN KEY(amenity_id) REFERENCES amenities(id));
CREATE TABLE reports (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, power_status VARCHAR(20) NOT NULL, wifi_status VARCHAR(20),
 crowd_level VARCHAR(20), safety_rating VARCHAR(20), comment VARCHAR(500), user_id BIGINT NOT NULL,
 location_id BIGINT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, verified BOOLEAN NOT NULL DEFAULT FALSE,
 FOREIGN KEY(user_id) REFERENCES users(id), FOREIGN KEY(location_id) REFERENCES locations(id)
);
